highlighter: pygments
safe: true
lsi: false
timezone: GB-Eire
...
defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      author: "Turtle"
      category: "project"
...
